package com.vintagemedia.rezziocoffeehousecentralapp.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// custom colors
// dark
val DarkGreen = Color(0xff002D2B)
val DarkRoyalBlue = Color(0xff00558C)
val DarkNavyBlue = Color(0xff151F42)
val DarkEarth = Color(0xff5A5447)
val DarkBrown = Color(0xff70503C)

// light
val LightGreen = Color(0xffCCFFFD)
val LightRoyalBlue = Color(0xffCCEBFF)
val LightNavyBlue = Color(0xffD8DEF3)
val LightEarth = Color(0xffE9E7E2)
val LightBrown = Color(0xffEDE4DE)

// from the Material tool
val md_theme_light_primary = Color(0xFF815600)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDDB1)
val md_theme_light_onPrimaryContainer = Color(0xFF291800)
val md_theme_light_secondary = Color(0xFF795900)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDFA0)
val md_theme_light_onSecondaryContainer = Color(0xFF261A00)
val md_theme_light_tertiary = Color(0xFF266C2B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFAAF5A4)
val md_theme_light_onTertiaryContainer = Color(0xFF002204)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF001946)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF001946)
val md_theme_light_surfaceVariant = Color(0xFFEFE0CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4F4539)
val md_theme_light_outline = Color(0xFF817567)
val md_theme_light_inverseOnSurface = Color(0xFFEEF0FF)
val md_theme_light_inverseSurface = Color(0xFF002C71)
val md_theme_light_inversePrimary = Color(0xFFFEBA4B)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF815600)

val md_theme_dark_primary = Color(0xFFFEBA4B)
val md_theme_dark_onPrimary = Color(0xFF442B00)
val md_theme_dark_primaryContainer = Color(0xFF624000)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDB1)
val md_theme_dark_secondary = Color(0xFFF3BF48)
val md_theme_dark_onSecondary = Color(0xFF402D00)
val md_theme_dark_secondaryContainer = Color(0xFF5C4300)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDFA0)
val md_theme_dark_tertiary = Color(0xFF8FD88A)
val md_theme_dark_onTertiary = Color(0xFF00390B)
val md_theme_dark_tertiaryContainer = Color(0xFF055315)
val md_theme_dark_onTertiaryContainer = Color(0xFFAAF5A4)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF000818)
val md_theme_dark_onBackground = Color(0xFFDAE2FF)
val md_theme_dark_surface = Color(0xFF00091A)
val md_theme_dark_onSurface = Color(0xFFDAE2FF)
val md_theme_dark_surfaceVariant = Color(0xFF4F4539)
val md_theme_dark_onSurfaceVariant = Color(0xFFD3C4B4)
val md_theme_dark_outline = Color(0xFF9B8F80)
val md_theme_dark_inverseOnSurface = Color(0xFF001946)
val md_theme_dark_inverseSurface = Color(0xFFDAE2FF)
val md_theme_dark_inversePrimary = Color(0xFF815600)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFEBA4B)
